version: "3.2"

volumes:
   ipfs-staging:
   ipfs-data:

services:
 minio:
    image: ipfs/go-ipfs:latest
    volumes:
      - ipfs-staging:/export
      - ipfs-data:/data/ipfs
    ports:
     - "8080:8080"
     - "4001:4001"
     - "127.0.0.1:5001:5001"
    network_mode: bridge